### Authorize

POST http://127.0.0.1:8080/api/auth
Content-Type: application/json

{
    "method": "password",
    "username": "admin",
    "password": "7VKL8dfYZTOeKjgt"
}

### Register

PUT http://127.0.0.1:8080/api/auth
Content-Type: application/json

{
    "username": "AxtTom",
    "password": "Asdf!1234",
    "confirm": "Asdf!1234"
}

### Get Current User

GET  http://127.0.0.1:8080/api/auth
Authorization: nl/c9y+f8Xm1uwY3YHFBMxBUxPAGzdRN4IUonVhHBZTdQArpqndbPHKa9K7LqE/l

### Delete Current Sessions

DELETE  http://127.0.0.1:8080/api/auth
Authorization: nl/c9y+f8Xm1uwY3YHFBMxBUxPAGzdRN4IUonVhHBZTdQArpqndbPHKa9K7LqE/l

###