### Authorize

POST http://127.0.0.1:8080/api/auth
Content-Type: application/json

{
    "method": "password",
    "username": "axttom",
    "password": "Asdf!1234"
}

### Register

PUT http://127.0.0.1:8080/api/auth
Content-Type: application/json

{
    "username": "AxtTom",
    "password": "Asdf!1234",
    "confirm": "Asdf!1234"
}

### Get Current User

GET  http://127.0.0.1:8080/api/auth
Authorization: 77JY6ryXfS1TzQcvdOO2iV+MvvOOuZtrGQOrc0JjdOSKieNHR5rQUbnAdafARjJh

### Delete All Sessions

DELETE  http://127.0.0.1:8080/api/auth
Authorization: 77JY6ryXfS1TzQcvdOO2iV+MvvOOuZtrGQOrc0JjdOSKieNHR5rQUbnAdafARjJh